[{'resultId': 655365,
  'value': 149.98399999998804,
  'time': 149.984,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 655365,
   'result': 'START_OF_MOVEMENT',
   'description': 'Absolute time from the start of recording to start of movement',
   'name': 'Start of Movement',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 655366,
  'value': 19.14290905813948,
  'time': 149.984,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 655366,
   'result': 'START_OF_MOVEMENT_THRESHOLD',
   'description': 'Threshold used for start of movement detection',
   'name': 'Start of Movement Detection Threshold',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 655367,
  'value': 149.98399999998804,
  'time': 149.984,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 655367,
   'result': 'START_OF_INTEGRATION',
   'description': 'Start time point for impulse, velocity and displacement integration',
   'name': 'Start of Integration',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553602,
  'value': 150.64199999999119,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553602,
   'result': 'BEGIN_CONCENTRIC_PHASE',
   'description': 'Asbolute time from the start of recording to the start of the concentric phase',
   'name': 'Start of Concentric Phase',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553603,
  'value': -36.030657282113815,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553603,
   'result': 'COUNTERMOVEMENT_DEPTH',
   'description': 'The amount of displacement the CM goes through from contact (zero position) to the lowest value. Note if the hips and knees are flexed at contact this is still the reference zero position.',
   'name': 'Countermovement Depth',
   'unit': 'Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553604,
  'value': 52.929,
  'time': 150.846,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553604,
   'result': 'BODYMASS_RELATIVE_TAKEOFF_POWER',
   'description': 'Peak power divided by body mass',
   'name': 'Peak Power / BM',
   'unit': 'Watt Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553606,
  'value': 0.5660000000027026,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553606,
   'result': 'FLIGHT_TIME',
   'description': 'The time interval between take-off and landing',
   'name': 'Flight Time',
   'unit': 'Millisecond',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553607,
  'value': 39.270239592875015,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553607,
   'result': 'JUMP_HEIGHT',
   'description': 'Jump height calculated from flight time',
   'name': 'Jump Height (Flight Time)',
   'unit': 'Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553608,
  'value': 618.2665803871299,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553608,
   'result': 'JUMP_HEIGHT_RELATIVE_LANDING_RFD',
   'description': 'Jump Height (FT) Relative Landing RFD',
   'name': 'Jump Height (FT) Relative Landing RFD',
   'unit': 'Newton Per Second Per Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553609,
  'value': 59.354,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553609,
   'result': 'JUMP_HEIGHT_RELATIVE_PEAK_LANDING_FORCE',
   'description': 'Jump Height (FT) Relative Peak Landing Force',
   'name': 'Jump Height (FT) Relative Peak Landing Force',
   'unit': 'Newton Per Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553610,
  'value': 40.45822482952112,
  'time': 151.192,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553610,
   'result': 'IMPULSE_JUMP_HEIGHT',
   'description': 'Jump height taken from the max displacement of the CM during the flight phase subtracting the displacement at the instant of take-off',
   'name': 'Jump Height (Imp-Dis)',
   'unit': 'Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553611,
  'value': 40.737879353736105,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553611,
   'result': 'JUMP_HEIGHT_IMP_MOM',
   'description': 'Jump height is determined from the Kinetic energy relationship after establishing the velocity at the instant of take-off (derived by determining the change in velocity from the impulse measurment throughout the contact phase, utilises the trapezium/simpsons rule)',
   'name': 'Jump Height (Imp-Mom)',
   'unit': 'Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553612,
  'value': 24279.477,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553612,
   'result': 'LANDING_RFD',
   'description': 'Landing Rate of Force Development',
   'name': 'Landing RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553612,
  'value': 14626.028,
  'time': 151.568,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553612,
   'result': 'LANDING_RFD',
   'description': 'Landing Rate of Force Development',
   'name': 'Landing RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553612,
  'value': 9400.824,
  'time': 151.568,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553612,
   'result': 'LANDING_RFD',
   'description': 'Landing Rate of Force Development',
   'name': 'Landing RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553612,
  'value': -35.7,
  'time': 151.568,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553612,
   'result': 'LANDING_RFD',
   'description': 'Landing Rate of Force Development',
   'name': 'Landing RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553613,
  'value': 15.460732597954488,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553613,
   'result': 'JUMP_HEIGHT_INCHES',
   'description': 'Jump height calculated from flight time, in inches',
   'name': 'Jump Height (Flight Time) in Inches',
   'unit': 'Inch',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553614,
  'value': 16.03854383944526,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553614,
   'result': 'JUMP_HEIGHT_INCHES_IMP_MOM',
   'description': 'Jump height is determined from the Kinetic energy relationship after establishing the velocity at the instant of take-off (derived by determining the change in velocity from the impulse measurment throughout the contact phase, utilises the trapezium/simpsons rule)',
   'name': 'Jump Height (Imp-Mom) in Inches',
   'unit': 'Inch',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553615,
  'value': 2.763,
  'time': 152.47,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553615,
   'result': 'MEAN_LANDING_ACCELERATION',
   'description': 'The average acceleration during landing',
   'name': 'Mean Landing Acceleration',
   'unit': 'Meter Per Second Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553616,
  'value': 965.767,
  'time': 152.47,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553616,
   'result': 'MEAN_LANDING_POWER',
   'description': 'The average power (force x velocity) during landing',
   'name': 'Mean Landing Power',
   'unit': 'Watt',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553617,
  'value': -0.088,
  'time': 152.47,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553617,
   'result': 'MEAN_LANDING_VELOCITY',
   'description': 'The average velocity during landing',
   'name': 'Mean Landing Velocity',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553618,
  'value': 10.653,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553618,
   'result': 'MEAN_TAKEOFF_ACCELERATION',
   'description': 'Mean Takeoff Acceleration',
   'name': 'Mean Takeoff Acceleration',
   'unit': 'Meter Per Second Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553619,
  'value': 1706.506,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553619,
   'result': 'MEAN_TAKEOFF_FORCE',
   'description': 'The average force in the concentric phase',
   'name': 'Concentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553619,
  'value': 894.17,
  'time': 150.906,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553619,
   'result': 'MEAN_TAKEOFF_FORCE',
   'description': 'The average force in the concentric phase',
   'name': 'Concentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553619,
  'value': 812.336,
  'time': 150.906,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553619,
   'result': 'MEAN_TAKEOFF_FORCE',
   'description': 'The average force in the concentric phase',
   'name': 'Concentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553619,
  'value': -9.2,
  'time': 150.906,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553619,
   'result': 'MEAN_TAKEOFF_FORCE',
   'description': 'The average force in the concentric phase',
   'name': 'Concentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553620,
  'value': 819.7964341085293,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553620,
   'result': 'MEAN_ECCENTRIC_FORCE',
   'description': 'The average force in the eccentric phase',
   'name': 'Eccentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553620,
  'value': 452.71736434108635,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553620,
   'result': 'MEAN_ECCENTRIC_FORCE',
   'description': 'The average force in the eccentric phase',
   'name': 'Eccentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553620,
  'value': 367.07906976744283,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553620,
   'result': 'MEAN_ECCENTRIC_FORCE',
   'description': 'The average force in the eccentric phase',
   'name': 'Eccentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553620,
  'value': -18.91650316931999,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553620,
   'result': 'MEAN_ECCENTRIC_FORCE',
   'description': 'The average force in the eccentric phase',
   'name': 'Eccentric Mean Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553621,
  'value': 446.5346262587147,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553621,
   'result': 'MEAN_ECCENTRIC_POWER',
   'description': 'Eccentric Mean Power',
   'name': 'Eccentric Mean Power',
   'unit': 'Watt',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553622,
  'value': 48.03945685073386,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553622,
   'result': 'MEAN_ECC_CON_RATIO',
   'description': 'Ratio of mean forces in the eccentric and concentric phases',
   'name': 'Eccentric:Concentric Mean Force Ratio',
   'unit': 'Percent',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553622,
  'value': 50.62988464328105,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553622,
   'result': 'MEAN_ECC_CON_RATIO',
   'description': 'Ratio of mean forces in the eccentric and concentric phases',
   'name': 'Eccentric:Concentric Mean Force Ratio',
   'unit': 'Percent',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553622,
  'value': 45.18807164602974,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553622,
   'result': 'MEAN_ECC_CON_RATIO',
   'description': 'Ratio of mean forces in the eccentric and concentric phases',
   'name': 'Eccentric:Concentric Mean Force Ratio',
   'unit': 'Percent',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553622,
  'value': -10.748223180029463,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553622,
   'result': 'MEAN_ECC_CON_RATIO',
   'description': 'Ratio of mean forces in the eccentric and concentric phases',
   'name': 'Eccentric:Concentric Mean Force Ratio',
   'unit': 'Percent',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553623,
  'value': 2691.3,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553623,
   'result': 'MEAN_CONCENTRIC_POWER',
   'description': 'The average power (force x velocity) in the concentric phase',
   'name': 'Concentric Mean Power',
   'unit': 'Watt',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553624,
  'value': 32.266,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553624,
   'result': 'BODYMASS_RELATIVE_MEAN_CONCENTRIC_POWER',
   'description': 'The average power (force x velocity) in the concentric phase divided by body mass',
   'name': 'Concentric Mean Power / BM',
   'unit': 'Watt Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553625,
  'value': 5.353490304024874,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553625,
   'result': 'BODYMASS_RELATIVE_MEAN_ECCENTRIC_POWER',
   'description': 'The average power (force x velocity) in the eccentric phase divided by body mass',
   'name': 'Eccentric Mean Power / BM',
   'unit': 'Watt Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553626,
  'value': 1.769,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553626,
   'result': 'MEAN_TAKEOFF_VELOCITY',
   'description': 'The average velocity during the concentric phase',
   'name': 'Concentric Mean Velocity',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553627,
  'value': 18.138,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553627,
   'result': 'PEAK_LANDING_ACCELERATION',
   'description': 'Peak acceleration during landing',
   'name': 'Peak Landing Acceleration',
   'unit': 'Meter Per Second Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553628,
  'value': 2330.8297674418604,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553628,
   'result': 'PEAK_LANDING_FORCE',
   'description': 'Peak force during landing',
   'name': 'Peak Landing Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553628,
  'value': 1433.351,
  'time': 151.57,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553628,
   'result': 'PEAK_LANDING_FORCE',
   'description': 'Peak force during landing',
   'name': 'Peak Landing Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553628,
  'value': 902.479,
  'time': 151.568,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553628,
   'result': 'PEAK_LANDING_FORCE',
   'description': 'Peak force during landing',
   'name': 'Peak Landing Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553628,
  'value': -37,
  'time': 151.568,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553628,
   'result': 'PEAK_LANDING_FORCE',
   'description': 'Peak force during landing',
   'name': 'Peak Landing Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553629,
  'value': 4895.12,
  'time': 151.536,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553629,
   'result': 'PEAK_LANDING_POWER',
   'description': 'Peak power (force x velocity) during landing',
   'name': 'Peak Landing Power',
   'unit': 'Watt',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553630,
  'value': 1.007,
  'time': 152.042,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553630,
   'result': 'PEAK_LANDING_VELOCITY',
   'description': 'Peak velocity during landing',
   'name': 'Peak Landing Velocity',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553631,
  'value': 15.86,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553631,
   'result': 'PEAK_TAKEOFF_ACCELERATION',
   'description': 'Peak acceleration during takeoff',
   'name': 'Peak Takeoff Acceleration',
   'unit': 'Meter Per Second Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553632,
  'value': 2140.8297674418604,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553632,
   'result': 'PEAK_TAKEOFF_FORCE',
   'description': 'Peak force over the entire takeoff phase',
   'name': 'Takeoff Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553632,
  'value': 1146.351,
  'time': 150.646,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553632,
   'result': 'PEAK_TAKEOFF_FORCE',
   'description': 'Peak force over the entire takeoff phase',
   'name': 'Takeoff Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553632,
  'value': 1007.479,
  'time': 150.666,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553632,
   'result': 'PEAK_TAKEOFF_FORCE',
   'description': 'Peak force over the entire takeoff phase',
   'name': 'Takeoff Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553632,
  'value': -12.1,
  'time': 150.652,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553632,
   'result': 'PEAK_TAKEOFF_FORCE',
   'description': 'Peak force over the entire takeoff phase',
   'name': 'Takeoff Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553633,
  'value': 4414.825,
  'time': 150.846,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553633,
   'result': 'PEAK_TAKEOFF_POWER',
   'description': 'The maximum power (force x velocity) value in the concentric phase or from start of movement if there is no concentric phase',
   'name': 'Peak Power',
   'unit': 'Watt',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553634,
  'value': 2.935,
  'time': 150.886,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553634,
   'result': 'PEAK_TAKEOFF_VELOCITY',
   'description': 'The highest vertical velocity value just prior to take-off',
   'name': 'Concentric Peak Velocity',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553637,
  'value': 999.9999999952252,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553637,
   'result': 'CONCENTRIC_RFD',
   'description': 'Rate of force development over the concentric phase',
   'name': 'Concentric RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553637,
  'value': -99.99999999952252,
  'time': 150.652,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553637,
   'result': 'CONCENTRIC_RFD',
   'description': 'Rate of force development over the concentric phase',
   'name': 'Concentric RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553637,
  'value': 1099.9999999947477,
  'time': 150.652,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553637,
   'result': 'CONCENTRIC_RFD',
   'description': 'Rate of force development over the concentric phase',
   'name': 'Concentric RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553637,
  'value': 100,
  'time': 150.652,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553637,
   'result': 'CONCENTRIC_RFD',
   'description': 'Rate of force development over the concentric phase',
   'name': 'Concentric RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553638,
  'value': -2089.9999999900206,
  'time': 150.742,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553638,
   'result': 'CONCENTRIC_RFD_100',
   'description': 'Rate of force development during the first 100ms of the concentric phase',
   'name': 'Concentric RFD - 100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553638,
  'value': -1509.99999999279,
  'time': 150.742,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553638,
   'result': 'CONCENTRIC_RFD_100',
   'description': 'Rate of force development during the first 100ms of the concentric phase',
   'name': 'Concentric RFD - 100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553638,
  'value': -579.9999999972306,
  'time': 150.742,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553638,
   'result': 'CONCENTRIC_RFD_100',
   'description': 'Rate of force development during the first 100ms of the concentric phase',
   'name': 'Concentric RFD - 100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553638,
  'value': -100,
  'time': 150.742,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553638,
   'result': 'CONCENTRIC_RFD_100',
   'description': 'Rate of force development during the first 100ms of the concentric phase',
   'name': 'Concentric RFD - 100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553639,
  'value': -2329.9999999888746,
  'time': 150.842,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553639,
   'result': 'CONCENTRIC_RFD_200',
   'description': 'Rate of force development during the first 200ms of the concentric phase',
   'name': 'Concentric RFD - 200ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553639,
  'value': -1434.999999993148,
  'time': 150.842,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553639,
   'result': 'CONCENTRIC_RFD_200',
   'description': 'Rate of force development during the first 200ms of the concentric phase',
   'name': 'Concentric RFD - 200ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553639,
  'value': -894.9999999957265,
  'time': 150.842,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553639,
   'result': 'CONCENTRIC_RFD_200',
   'description': 'Rate of force development during the first 200ms of the concentric phase',
   'name': 'Concentric RFD - 200ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553639,
  'value': -60.33519553072626,
  'time': 150.842,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553639,
   'result': 'CONCENTRIC_RFD_200',
   'description': 'Rate of force development during the first 200ms of the concentric phase',
   'name': 'Concentric RFD - 200ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553640,
  'value': -1199.9999999942702,
  'time': 150.692,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553640,
   'result': 'CONCENTRIC_RFD_50',
   'description': 'Rate of force development during the first 50ms of the concentric phase',
   'name': 'Concentric RFD - 50ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553640,
  'value': -1179.9999999943657,
  'time': 150.692,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553640,
   'result': 'CONCENTRIC_RFD_50',
   'description': 'Rate of force development during the first 50ms of the concentric phase',
   'name': 'Concentric RFD - 50ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553640,
  'value': -19.999999999904503,
  'time': 150.692,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553640,
   'result': 'CONCENTRIC_RFD_50',
   'description': 'Rate of force development during the first 50ms of the concentric phase',
   'name': 'Concentric RFD - 50ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553640,
  'value': -100,
  'time': 150.692,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553640,
   'result': 'CONCENTRIC_RFD_50',
   'description': 'Rate of force development during the first 50ms of the concentric phase',
   'name': 'Concentric RFD - 50ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553642,
  'value': 0.010000000000047748,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553642,
   'result': 'TIME_TO_PEAK_FORCE',
   'description': 'Time between start of the concentric phase to peak force',
   'name': 'Concentric Time to Peak Force',
   'unit': 'Millisecond',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553643,
  'value': 0.9220000000044024,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553643,
   'result': 'CONTRACTION_TIME',
   'description': 'Time on the ground between start of movement and takeoff',
   'name': 'Contraction Time',
   'unit': 'Millisecond',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553644,
  'value': 0.6580000000031418,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553644,
   'result': 'ECCENTRIC_TIME',
   'description': 'Duration of the eccentric phase',
   'name': 'Eccentric Duration',
   'unit': 'Millisecond',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553645,
  'value': 0.6680000000031896,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553645,
   'result': 'START_TO_PEAK_FORCE_TIME',
   'description': 'Time between start of movement and peak force',
   'name': 'Movement Start to Peak Force',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553646,
  'value': 0.862,
  'time': 150.846,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553646,
   'result': 'START_TO_PEAK_POWER_TIME',
   'description': 'Time between start of movement and peak power',
   'name': 'Movement Start to Peak Power',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553647,
  'value': 18.138,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553647,
   'result': 'WEIGHT_RELATIVE_PEAK_LANDING_FORCE',
   'description': 'Landing net (above body-weight) peak force relative to body mass',
   'name': 'Landing Net Peak Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553648,
  'value': 15.86,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553648,
   'result': 'WEIGHT_RELATIVE_PEAK_TAKEOFF_FORCE',
   'description': 'Peak net (above body-weight) takeoff force relative to body mass',
   'name': 'Peak Net Takeoff Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553649,
  'value': 11.988970147407088,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553649,
   'result': 'RELATIVE_CONCENTRIC_RFD',
   'description': 'Rate of force development over the concentric phase to peak force relative to body mass',
   'name': 'Concentric RFD / BM',
   'unit': 'Newton Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553655,
  'value': 2.82666632117877,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553655,
   'result': 'TAKEOFF_VELOCITY',
   'description': 'The vertical velocity at the instant of take-off',
   'name': 'Vertical Velocity at Takeoff',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553657,
  'value': 0.26400000000126056,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553657,
   'result': 'CONCENTRIC_DURATION',
   'description': 'Length of the concentric phase',
   'name': 'Concentric Duration',
   'unit': 'Millisecond',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553658,
  'value': 140.12158054711247,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553658,
   'result': 'CONCENTRIC_ECCENTRIC_DURATION_RATIO',
   'description': 'Ratio of total contraction time to eccentric duration as %',
   'name': 'Contraction Time:Eccentric Duration',
   'unit': 'Percent',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553659,
  'value': 249.24242424242425,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553659,
   'result': 'ECCENTRIC_CONCENTRIC_DURATION_RATIO',
   'description': 'Ratio of eccentric to concentric duration as %',
   'name': 'Eccentric:Concentric Duration',
   'unit': 'Percent',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553660,
  'value': 0.613882863340564,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553660,
   'result': 'FLIGHT_CONTRACTION_TIME_RATIO',
   'description': 'Ratio of flight time to contraction time',
   'name': 'Flight Time:Contraction Time',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553661,
  'value': 0.8601823708206687,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553661,
   'result': 'FLIGHT_ECCENTRIC_TIME_RATIO',
   'description': 'Ratio of flight time to eccentric duration',
   'name': 'FlightTime:Eccentric Duration',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553662,
  'value': 150.25999999998936,
  'time': 150.26,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553662,
   'result': 'BEGIN_BRAKING_PHASE',
   'description': 'Absolute time from the start of recording to the start of braking phase (minimum force during eccentric phase)',
   'name': 'Start of Braking Phase',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553663,
  'value': 407.82976744186044,
  'time': 150.26,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553663,
   'result': 'MIN_ECCENTRIC_FORCE',
   'description': 'Minimum force during the eccentric phase',
   'name': 'Minimum Eccentric Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553664,
  'value': 0.382000000001824,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553664,
   'result': 'BRAKING_PHASE_DURATION',
   'description': 'The time period from minimum force to the start of the concentric phase ',
   'name': 'Braking Phase Duration',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553665,
  'value': 150.48999999999046,
  'time': 150.49,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553665,
   'result': 'BEGIN_ECC_DECEL_PHASE',
   'description': 'Absolute time from the start of recording to the start of eccentric deceleration phase (end of eccentric acceleration phase)',
   'name': 'Start of Eccentric Deceleration Phase',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553666,
  'value': 0.27600000000131786,
  'time': 150.26,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553666,
   'result': 'TIME_TO_BRAKING_PHASE',
   'description': 'Time period from the start of the movement to minimum force eccentric (braking) phase',
   'name': 'Time to Braking Phase',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553667,
  'value': 0.5060000000024161,
  'time': 150.49,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553667,
   'result': 'ECCENTRIC_ACCEL_PHASE_DURATION',
   'description': 'The time period from start of movement and to maximum negative velocity',
   'name': 'Eccentric Acceleration Phase Duration',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553668,
  'value': 0.15200000000072578,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553668,
   'result': 'ECCENTRIC_DECEL_PHASE_DURATION',
   'description': 'The time period from maximum negative velocity to zero velocity (start of concentric phase)',
   'name': 'Eccentric Deceleration Phase Duration',
   'unit': 'Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553669,
  'value': 41.431670281995665,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553669,
   'result': 'BEAKING_CONTRACTION_DURATION_RATIO',
   'description': 'Braking phase duration to contraction time ratio',
   'name': 'Braking Phase Duration:Contraction Time ',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553670,
  'value': 144.6969696969697,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553670,
   'result': 'BEAKING_CONCENTRIC_DURATION_RATIO',
   'description': 'Braking phase duration to concentric phase duration ratio',
   'name': 'Braking Phase Duration:Concentric Duration',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553671,
  'value': 925.840184108527,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553671,
   'result': 'MEAN_ECCENTRIC_BRAKING_FORCE',
   'description': 'Mean force during the eccentric braking phase (from minimum force to the end of the eccentric phase)',
   'name': 'Eccentric Mean Braking Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553672,
  'value': 1416.8687284808198,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553672,
   'result': 'MEAN_ECCENTRIC_DECELERATION_FORCE',
   'description': 'Mean force from during the eccentric deceleration phase.',
   'name': 'Eccentric Mean Deceleration Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553673,
  'value': 1643.8297674418604,
  'time': 150.846,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553673,
   'result': 'FORCE_AT_PEAK_POWER',
   'description': 'Force at point of peak power',
   'name': 'Force at Peak Power',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553673,
  'value': 847.3506976744186,
  'time': 150.846,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553673,
   'result': 'FORCE_AT_PEAK_POWER',
   'description': 'Force at point of peak power',
   'name': 'Force at Peak Power',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553673,
  'value': 796.4790697674418,
  'time': 150.846,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553673,
   'result': 'FORCE_AT_PEAK_POWER',
   'description': 'Force at point of peak power',
   'name': 'Force at Peak Power',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553673,
  'value': -6.003609608937078,
  'time': 150.846,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553673,
   'result': 'FORCE_AT_PEAK_POWER',
   'description': 'Force at point of peak power',
   'name': 'Force at Peak Power',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553674,
  'value': 65.2808545474047,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553674,
   'result': 'CONCENTRIC_IMPULSE_50MS',
   'description': 'Total net impulse over first 50ms of the concentric phase',
   'name': 'Concentric Impulse-50ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553674,
  'value': 56.290534883989714,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553674,
   'result': 'CONCENTRIC_IMPULSE_50MS',
   'description': 'Total net impulse over first 50ms of the concentric phase',
   'name': 'Concentric Impulse-50ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553674,
  'value': 49.88895348861029,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553674,
   'result': 'CONCENTRIC_IMPULSE_50MS',
   'description': 'Total net impulse over first 50ms of the concentric phase',
   'name': 'Concentric Impulse-50ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553674,
  'value': -11.372393970980326,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553674,
   'result': 'CONCENTRIC_IMPULSE_50MS',
   'description': 'Total net impulse over first 50ms of the concentric phase',
   'name': 'Concentric Impulse-50ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553675,
  'value': 123.94270909477778,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553675,
   'result': 'CONCENTRIC_IMPULSE_100MS',
   'description': 'Total net impulse over first 100ms of the concentric phase',
   'name': 'Concentric Impulse-100ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553675,
  'value': 107.89606976795706,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553675,
   'result': 'CONCENTRIC_IMPULSE_100MS',
   'description': 'Total net impulse over first 100ms of the concentric phase',
   'name': 'Concentric Impulse-100ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553675,
  'value': 97.84390697721135,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553675,
   'result': 'CONCENTRIC_IMPULSE_100MS',
   'description': 'Total net impulse over first 100ms of the concentric phase',
   'name': 'Concentric Impulse-100ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553675,
  'value': -9.316523588267902,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553675,
   'result': 'CONCENTRIC_IMPULSE_100MS',
   'description': 'Total net impulse over first 100ms of the concentric phase',
   'name': 'Concentric Impulse-100ms',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553676,
  'value': 157.44413600507727,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553676,
   'result': 'CONCENTRIC_IMPULSE_P1',
   'description': 'Net impulse during 1st 50% (time-wise) of concentric phase',
   'name': 'P1 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553676,
  'value': 139.06029209368725,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553676,
   'result': 'CONCENTRIC_IMPULSE_P1',
   'description': 'Net impulse during 1st 50% (time-wise) of concentric phase',
   'name': 'P1 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553676,
  'value': 126.35623720990561,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553676,
   'result': 'CONCENTRIC_IMPULSE_P1',
   'description': 'Net impulse during 1st 50% (time-wise) of concentric phase',
   'name': 'P1 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553676,
  'value': -9.13564518850766,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553676,
   'result': 'CONCENTRIC_IMPULSE_P1',
   'description': 'Net impulse during 1st 50% (time-wise) of concentric phase',
   'name': 'P1 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553677,
  'value': 78.41813600469992,
  'time': 150.774,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553677,
   'result': 'CONCENTRIC_IMPULSE_P2',
   'description': 'Net impulse during 2nd 50% (time-wise) of concentric phase',
   'name': 'P2 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553677,
  'value': 97.63629209348947,
  'time': 150.774,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553677,
   'result': 'CONCENTRIC_IMPULSE_P2',
   'description': 'Net impulse during 2nd 50% (time-wise) of concentric phase',
   'name': 'P2 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553677,
  'value': 88.75423720972607,
  'time': 150.774,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553677,
   'result': 'CONCENTRIC_IMPULSE_P2',
   'description': 'Net impulse during 2nd 50% (time-wise) of concentric phase',
   'name': 'P2 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553677,
  'value': -9.097083362463813,
  'time': 150.774,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553677,
   'result': 'CONCENTRIC_IMPULSE_P2',
   'description': 'Net impulse during 2nd 50% (time-wise) of concentric phase',
   'name': 'P2 Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553678,
  'value': 4510.4712041669445,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553678,
   'result': 'ECCENTRIC_BRAKING_RFD',
   'description': 'Eccentric RFD calculated from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553678,
  'value': 2409.326424858962,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553678,
   'result': 'ECCENTRIC_BRAKING_RFD',
   'description': 'Eccentric RFD calculated from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553678,
  'value': 2288.1355932094134,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553678,
   'result': 'ECCENTRIC_BRAKING_RFD',
   'description': 'Eccentric RFD calculated from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553678,
  'value': -5.030071077091309,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553678,
   'result': 'ECCENTRIC_BRAKING_RFD',
   'description': 'Eccentric RFD calculated from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553679,
  'value': 54.075904617755,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553679,
   'result': 'RELATIVE_ECCENTRIC_BRAKING_RFD',
   'description': 'Eccentric RFD calculated from the initiation of the active (braking) phase to the end of the eccentric phase realtive to body-weight',
   'name': 'Eccentric Braking RFD / BM',
   'unit': 'Newton Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553680,
  'value': 1569.9999999925035,
  'time': 150.36,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553680,
   'result': 'ECCENTRIC_BRAKING_RFD_100MS',
   'description': 'Eccentric RFD calculated over first 100ms of the braking phase',
   'name': 'Eccentric Braking RFD-100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553680,
  'value': 989.9999999952729,
  'time': 150.356,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553680,
   'result': 'ECCENTRIC_BRAKING_RFD_100MS',
   'description': 'Eccentric RFD calculated over first 100ms of the braking phase',
   'name': 'Eccentric Braking RFD-100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553680,
  'value': 759.9999999963711,
  'time': 150.388,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553680,
   'result': 'ECCENTRIC_BRAKING_RFD_100MS',
   'description': 'Eccentric RFD calculated over first 100ms of the braking phase',
   'name': 'Eccentric Braking RFD-100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553680,
  'value': -23.232323232323232,
  'time': 150.36,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553680,
   'result': 'ECCENTRIC_BRAKING_RFD_100MS',
   'description': 'Eccentric RFD calculated over first 100ms of the braking phase',
   'name': 'Eccentric Braking RFD-100ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553681,
  'value': 18.822683131429127,
  'time': 150.36,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553681,
   'result': 'RELATIVE_ECCENTRIC_BRAKING_RFD_100MS',
   'description': 'Eccentric RFD calculated over first 100ms of the braking phase relative to body mass',
   'name': 'Eccentric Braking RFD-100ms / BM',
   'unit': 'Newton Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553682,
  'value': 8631.578947327207,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553682,
   'result': 'ECCENTRIC_DECEL_RFD',
   'description': 'Rate of force development calculated over the eccentric deceleration phase',
   'name': 'Eccentric Deceleration RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553682,
  'value': 4197.36842103259,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553682,
   'result': 'ECCENTRIC_DECEL_RFD',
   'description': 'Rate of force development calculated over the eccentric deceleration phase',
   'name': 'Eccentric Deceleration RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553682,
  'value': 4434.210526294617,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553682,
   'result': 'ECCENTRIC_DECEL_RFD',
   'description': 'Rate of force development calculated over the eccentric deceleration phase',
   'name': 'Eccentric Deceleration RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553682,
  'value': 5.341246290801186,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553682,
   'result': 'ECCENTRIC_DECEL_RFD',
   'description': 'Rate of force development calculated over the eccentric deceleration phase',
   'name': 'Eccentric Deceleration RFD',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553683,
  'value': 103.4837423249875,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553683,
   'result': 'RELATIVE_ECCENTRIC_DECEL_RFD',
   'description': 'Rate of force development calculated over the eccentric deceleration phase relative to body mass',
   'name': 'Eccentric Deceleration RFD / BM',
   'unit': 'Newton Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553684,
  'value': 25.666344172663475,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553684,
   'result': 'RELATIVE_PEAK_TAKEOFF_FORCE',
   'description': 'Peak force over the entire takeoff phase relative to body mass',
   'name': 'Takeoff Peak Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553685,
  'value': 2140.8297674418604,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553685,
   'result': 'PEAK_CONCENTRIC_FORCE',
   'description': 'Peak force over the concentric phase',
   'name': 'Concentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553685,
  'value': 1146.3506976744186,
  'time': 150.646,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553685,
   'result': 'PEAK_CONCENTRIC_FORCE',
   'description': 'Peak force over the concentric phase',
   'name': 'Concentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553685,
  'value': 1007.4790697674418,
  'time': 150.666,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553685,
   'result': 'PEAK_CONCENTRIC_FORCE',
   'description': 'Peak force over the concentric phase',
   'name': 'Concentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553685,
  'value': -12.114235913032823,
  'time': 150.652,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553685,
   'result': 'PEAK_CONCENTRIC_FORCE',
   'description': 'Peak force over the concentric phase',
   'name': 'Concentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553686,
  'value': 25.666344172663475,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553686,
   'result': 'RELATIVE_PEAK_CONCENTRIC_FORCE',
   'description': 'Peak force over the concentric phase relative to body mass',
   'name': 'Concentric Peak Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553687,
  'value': 2130.8297674418604,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553687,
   'result': 'PEAK_ECCENTRIC_FORCE',
   'description': 'Peak force over the eccentric phase',
   'name': 'Eccentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553687,
  'value': 1145.3506976744186,
  'time': 150.64,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553687,
   'result': 'PEAK_ECCENTRIC_FORCE',
   'description': 'Peak force over the eccentric phase',
   'name': 'Eccentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553687,
  'value': 985.4790697674418,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553687,
   'result': 'PEAK_ECCENTRIC_FORCE',
   'description': 'Peak force over the eccentric phase',
   'name': 'Eccentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553687,
  'value': -13.958312351979938,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553687,
   'result': 'PEAK_ECCENTRIC_FORCE',
   'description': 'Peak force over the eccentric phase',
   'name': 'Eccentric Peak Force',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553688,
  'value': 25.54645447118883,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553688,
   'result': 'RELATIVE_PEAK_ECCENTRIC_FORCE',
   'description': 'Peak force over the eccentric phase relative to body mass',
   'name': 'Eccentric Peak Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553689,
  'value': 27.9442485006817,
  'time': 151.568,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553689,
   'result': 'RELATIVE_PEAK_LANDING_FORCE',
   'description': 'Peak force on landing relative to body mass',
   'name': 'Peak Landing Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553690,
  'value': 1186.2434995086965,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553690,
   'result': 'MEAN_ECC_CON_POWER_TIME',
   'description': 'Power during eccentric (converted to absolute values) + concentric phases, divided by the total contraction time',
   'name': 'Mean Eccentric+Concentric Power:Time',
   'unit': 'Watt Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553691,
  'value': 4782.038769121551,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553691,
   'result': 'LOWER_LIMB_STIFFNESS',
   'description': 'Change in vertical force divided by displacement of CoM during the eccentric phase',
   'name': 'Lower-Limb Stiffness',
   'unit': 'Newton Per Meter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553692,
  'value': 21630.025415391687,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553692,
   'result': 'CONCENTRIC_RPD',
   'description': 'Rate of power development from start of concentric phase to peak power',
   'name': 'Concentric RPD',
   'unit': 'Watt Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553693,
  'value': 259.32172899402576,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553693,
   'result': 'RELATIVE_CONCENTRIC_RPD',
   'description': 'Rate of power development from start of concentric phase to peak power relative to body mass',
   'name': 'Concentric RPD / BM',
   'unit': 'Watt Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553694,
  'value': 32324.00046811147,
  'time': 150.692,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553694,
   'result': 'CONCENTRIC_RPD_50MS',
   'description': 'Rate of power development for 50ms from start of the concentric phase',
   'name': 'Concentric RPD - 50ms',
   'unit': 'Watt Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553695,
  'value': 387.5314766588115,
  'time': 150.692,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553695,
   'result': 'RELATIVE_CONCENTRIC_RPD_50MS',
   'description': 'Rate of power development for 50ms from start of the concentric phase to peak power relative to body mass',
   'name': 'Concentric RPD-50ms / BM',
   'unit': 'Watt Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553696,
  'value': 28513.596690632796,
  'time': 150.742,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553696,
   'result': 'CONCENTRIC_RPD_100MS',
   'description': 'Rate of power development for 100ms from start of the concentric phase',
   'name': 'Concentric RPD - 100ms',
   'unit': 'Watt Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553697,
  'value': 341.8486595208344,
  'time': 150.742,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553697,
   'result': 'RELATIVE_CONCENTRIC_RPD_100MS',
   'description': 'Rate of power development for 100ms from start of the concentric phase to peak power relative to body mass',
   'name': 'Concentric RPD-100ms / BM',
   'unit': 'Watt Per Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553698,
  'value': 42.59245075128797,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553698,
   'result': 'RSI_MODIFIED',
   'description': 'Jump height (flight time) / Contraction time',
   'name': 'RSI-modified',
   'unit': 'RSIModified',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553699,
  'value': 1010.5737842042089,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553699,
   'result': 'TOTAL_WORK',
   'description': 'Integrating the power-time curve from the SoM through the concentric phase, until the power output reaches zero',
   'name': 'Total Work',
   'unit': 'Joule',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553700,
  'value': 2.6856949093987947,
  'time': 150.846,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553700,
   'result': 'VELOCITY_AT_PEAK_POWER',
   'description': 'Vertical velocity at the point of peak power during takeoff',
   'name': 'Velocity at Peak Power',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553701,
  'value': -1.0910719576052397,
  'time': 150.49,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553701,
   'result': 'ECCENTRIC_PEAK_VELOCITY',
   'description': 'Maximum negative velocity during the eccentric phase (ie. velocity at the start of the eccentric deceleration phase)',
   'name': 'Eccentric Peak Velocity',
   'unit': 'Meter Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553702,
  'value': 1246.8809644726718,
  'time': 150.574,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553702,
   'result': 'ECCENTRIC_PEAK_POWER',
   'description': 'Peak power during the eccentric phase',
   'name': 'Eccentric Peak Power',
   'unit': 'Watt',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553703,
  'value': 40.518408739983904,
  'time': 150.26,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553703,
   'result': 'ECCENTRIC_BRAKING_IMPULSE',
   'description': 'Net impulse from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553703,
  'value': 200.94396651258745,
  'time': 150.26,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553703,
   'result': 'ECCENTRIC_BRAKING_IMPULSE',
   'description': 'Net impulse from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553703,
  'value': 152.0400046518888,
  'time': 150.26,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553703,
   'result': 'ECCENTRIC_BRAKING_IMPULSE',
   'description': 'Net impulse from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553703,
  'value': -24.33711382801594,
  'time': 150.26,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553703,
   'result': 'ECCENTRIC_BRAKING_IMPULSE',
   'description': 'Net impulse from the initiation of the active (braking) phase to the end of the eccentric phase',
   'name': 'Eccentric Braking Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553704,
  'value': 90.91627782359684,
  'time': 150.49,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553704,
   'result': 'ECCENTRIC_DECEL_IMPULSE',
   'description': 'Net impulse from the start of eccentric deceleration to the end of the eccentric phase',
   'name': 'Eccentric Deceleration Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553704,
  'value': 122.51330604709663,
  'time': 150.49,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553704,
   'result': 'ECCENTRIC_DECEL_IMPULSE',
   'description': 'Net impulse from the start of eccentric deceleration to the end of the eccentric phase',
   'name': 'Eccentric Deceleration Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553704,
  'value': 92.7348186050939,
  'time': 150.49,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553704,
   'result': 'ECCENTRIC_DECEL_IMPULSE',
   'description': 'Net impulse from the start of eccentric deceleration to the end of the eccentric phase',
   'name': 'Eccentric Deceleration Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553704,
  'value': -24.30632916767038,
  'time': 150.49,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553704,
   'result': 'ECCENTRIC_DECEL_IMPULSE',
   'description': 'Net impulse from the start of eccentric deceleration to the end of the eccentric phase',
   'name': 'Eccentric Deceleration Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553712,
  'value': 235.86227200977717,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553712,
   'result': 'CONCENTRIC_IMPULSE',
   'description': 'Area under the Fz curve from transition point at zero velocity (max negative displacement) (start of concentric phase) to take-off - net impulse',
   'name': 'Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553712,
  'value': 236.69658418717674,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553712,
   'result': 'CONCENTRIC_IMPULSE',
   'description': 'Area under the Fz curve from transition point at zero velocity (max negative displacement) (start of concentric phase) to take-off - net impulse',
   'name': 'Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553712,
  'value': 215.1104744196326,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553712,
   'result': 'CONCENTRIC_IMPULSE',
   'description': 'Area under the Fz curve from transition point at zero velocity (max negative displacement) (start of concentric phase) to take-off - net impulse',
   'name': 'Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553712,
  'value': -9.119738606144868,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553712,
   'result': 'CONCENTRIC_IMPULSE',
   'description': 'Area under the Fz curve from transition point at zero velocity (max negative displacement) (start of concentric phase) to take-off - net impulse',
   'name': 'Concentric Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553713,
  'value': 2130.8297674418604,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553713,
   'result': 'FORCE_AT_ZERO_VELOCITY',
   'description': 'The combined (total) force at the instant velocity is zero prior to takeoff',
   'name': 'Force at Zero Velocity',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553713,
  'value': 1145.3506976744186,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553713,
   'result': 'FORCE_AT_ZERO_VELOCITY',
   'description': 'The combined (total) force at the instant velocity is zero prior to takeoff',
   'name': 'Force at Zero Velocity',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553713,
  'value': 985.4790697674418,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553713,
   'result': 'FORCE_AT_ZERO_VELOCITY',
   'description': 'The combined (total) force at the instant velocity is zero prior to takeoff',
   'name': 'Force at Zero Velocity',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553713,
  'value': -13.958312351979938,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553713,
   'result': 'FORCE_AT_ZERO_VELOCITY',
   'description': 'The combined (total) force at the instant velocity is zero prior to takeoff',
   'name': 'Force at Zero Velocity',
   'unit': 'Newton',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553714,
  'value': 653.40337894354,
  'time': 151.482,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553714,
   'result': 'POSITIVE_IMPULSE',
   'description': 'Area above BW in takeoff and landing phases',
   'name': 'Positive Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553714,
  'value': 795.1076697712358,
  'time': 151.482,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553714,
   'result': 'POSITIVE_IMPULSE',
   'description': 'Area above BW in takeoff and landing phases',
   'name': 'Positive Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553714,
  'value': 643.4749069798186,
  'time': 151.482,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553714,
   'result': 'POSITIVE_IMPULSE',
   'description': 'Area above BW in takeoff and landing phases',
   'name': 'Positive Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553714,
  'value': -19.07072067799877,
  'time': 151.482,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553714,
   'result': 'POSITIVE_IMPULSE',
   'description': 'Area above BW in takeoff and landing phases',
   'name': 'Positive Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553716,
  'value': -91.0063119838534,
  'time': 149.984,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553716,
   'result': 'ECCENTRIC_UNLOADING_IMPULSE',
   'description': 'Net impulse from start of movement to start of the deceleration phase',
   'name': 'Eccentric Unloading Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553716,
  'value': 174.61545302408967,
  'time': 149.984,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553716,
   'result': 'ECCENTRIC_UNLOADING_IMPULSE',
   'description': 'Net impulse from start of movement to start of the deceleration phase',
   'name': 'Eccentric Unloading Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553716,
  'value': 148.2724093030338,
  'time': 149.984,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553716,
   'result': 'ECCENTRIC_UNLOADING_IMPULSE',
   'description': 'Net impulse from start of movement to start of the deceleration phase',
   'name': 'Eccentric Unloading Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553716,
  'value': -15.0863186876259,
  'time': 149.984,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553716,
   'result': 'ECCENTRIC_UNLOADING_IMPULSE',
   'description': 'Net impulse from start of movement to start of the deceleration phase',
   'name': 'Eccentric Unloading Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553717,
  'value': 335.86540801458085,
  'time': 150.488,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553717,
   'result': 'POSITIVE_TAKEOFF_IMPULSE',
   'description': 'Area above BW in the takeoff phase',
   'name': 'Positive Takeoff Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553717,
  'value': 355.8145776761168,
  'time': 150.488,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553717,
   'result': 'POSITIVE_TAKEOFF_IMPULSE',
   'description': 'Area above BW in the takeoff phase',
   'name': 'Positive Takeoff Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553717,
  'value': 305.58866976890175,
  'time': 150.488,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553717,
   'result': 'POSITIVE_TAKEOFF_IMPULSE',
   'description': 'Area above BW in the takeoff phase',
   'name': 'Positive Takeoff Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553717,
  'value': -14.115753276678172,
  'time': 150.488,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553717,
   'result': 'POSITIVE_TAKEOFF_IMPULSE',
   'description': 'Area above BW in the takeoff phase',
   'name': 'Positive Takeoff Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553718,
  'value': 5941.689463723999,
  'time': 150.652,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553718,
   'result': 'CMJ_STIFFNESS',
   'description': 'Peak force during takeoff / displacement at start of concentric phase (min displacement)',
   'name': 'CMJ Stiffness',
   'unit': 'Newton Per Meter',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553718,
  'value': 3181.5980727153847,
  'time': 150.646,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553718,
   'result': 'CMJ_STIFFNESS',
   'description': 'Peak force during takeoff / displacement at start of concentric phase (min displacement)',
   'name': 'CMJ Stiffness',
   'unit': 'Newton Per Meter',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553718,
  'value': 2796.1717763821375,
  'time': 150.666,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553718,
   'result': 'CMJ_STIFFNESS',
   'description': 'Peak force during takeoff / displacement at start of concentric phase (min displacement)',
   'name': 'CMJ Stiffness',
   'unit': 'Newton Per Meter',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553718,
  'value': -12.114235913032823,
  'time': 150.652,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553718,
   'result': 'CMJ_STIFFNESS',
   'description': 'Peak force during takeoff / displacement at start of concentric phase (min displacement)',
   'name': 'CMJ Stiffness',
   'unit': 'Newton Per Meter',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553720,
  'value': 20.459254995458437,
  'time': 150.906,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553720,
   'result': 'BODYMASS_RELATIVE_MEAN_TAKEOFF_FORCE',
   'description': 'The average force in the concentric phase relative to body mass',
   'name': 'Concentric Mean Force / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553722,
  'value': 14.948818660504399,
  'time': 150.574,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553722,
   'result': 'BODYMASS_RELATIVE_ECCENTRIC_PEAK_POWER',
   'description': 'Eccentric Peak Power divided by Body Mass',
   'name': 'Eccentric Peak Power / BM',
   'unit': 'Watt Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553724,
  'value': 0.28243042411853375,
  'time': 150.574,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553724,
   'result': 'ECC_CON_PEAK_POWER_RATIO',
   'description': 'Ratio of Eccentric Peak Power to Concentric Peak Power',
   'name': 'Eccentric Peak Power:Concentric Peak Power',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553725,
  'value': 0.49806958832795833,
  'time': 150.774,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553725,
   'result': 'CON_P2_CON_P1_IMPULSE_RATIO',
   'description': 'Ratio of P2 Concentric Impulse to P1 Concentric Impulse',
   'name': 'P2 Concentric Impulse:P1 Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553725,
  'value': 0.7021148210138252,
  'time': 150.774,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553725,
   'result': 'CON_P2_CON_P1_IMPULSE_RATIO',
   'description': 'Ratio of P2 Concentric Impulse to P1 Concentric Impulse',
   'name': 'P2 Concentric Impulse:P1 Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553725,
  'value': 0.702412790769368,
  'time': 150.774,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553725,
   'result': 'CON_P2_CON_P1_IMPULSE_RATIO',
   'description': 'Ratio of P2 Concentric Impulse to P1 Concentric Impulse',
   'name': 'P2 Concentric Impulse:P1 Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553725,
  'value': 0.042420889747250584,
  'time': 150.774,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553725,
   'result': 'CON_P2_CON_P1_IMPULSE_RATIO',
   'description': 'Ratio of P2 Concentric Impulse to P1 Concentric Impulse',
   'name': 'P2 Concentric Impulse:P1 Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553726,
  'value': 0.5254876417439073,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553726,
   'result': 'CON_100MS_CON_IMPULSE_RATIO',
   'description': 'Ratio of Concentric Impulse-100ms to Concentric Impulse',
   'name': 'Concentric Impulse-100ms:Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553726,
  'value': 0.4558412625111403,
  'time': 150.642,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553726,
   'result': 'CON_100MS_CON_IMPULSE_RATIO',
   'description': 'Ratio of Concentric Impulse-100ms to Concentric Impulse',
   'name': 'Concentric Impulse-100ms:Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553726,
  'value': 0.4548542196338598,
  'time': 150.642,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553726,
   'result': 'CON_100MS_CON_IMPULSE_RATIO',
   'description': 'Ratio of Concentric Impulse-100ms to Concentric Impulse',
   'name': 'Concentric Impulse-100ms:Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553726,
  'value': -0.216532148020803,
  'time': 150.642,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553726,
   'result': 'CON_100MS_CON_IMPULSE_RATIO',
   'description': 'Ratio of Concentric Impulse-100ms to Concentric Impulse',
   'name': 'Concentric Impulse-100ms:Concentric Impulse',
   'unit': 'No Unit',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553727,
  'value': 150.29565767513617,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553727,
   'result': 'LANDING_IMPULSE',
   'description': 'Absolute Impulse from Landing to Peak Landing Force',
   'name': 'Landing Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553727,
  'value': 100.51036837257296,
  'time': 151.472,
  'limb': 'Left',
  'repeat': 0,
  'definition': {'id': 6553727,
   'result': 'LANDING_IMPULSE',
   'description': 'Absolute Impulse from Landing to Peak Landing Force',
   'name': 'Landing Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553727,
  'value': 52.64699069792577,
  'time': 151.472,
  'limb': 'Right',
  'repeat': 0,
  'definition': {'id': 6553727,
   'result': 'LANDING_IMPULSE',
   'description': 'Absolute Impulse from Landing to Peak Landing Force',
   'name': 'Landing Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553727,
  'value': -47.62033852788867,
  'time': 151.472,
  'limb': 'Asym',
  'repeat': 0,
  'definition': {'id': 6553727,
   'result': 'LANDING_IMPULSE',
   'description': 'Absolute Impulse from Landing to Peak Landing Force',
   'name': 'Landing Impulse',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': True}},
 {'resultId': 6553728,
  'value': 35019.999999832784,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553728,
   'result': 'LANDING_RFD_50',
   'description': 'Rate of force development over the first 50ms from landing',
   'name': 'Landing RFD 50ms',
   'unit': 'Newton Per Second',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553730,
  'value': 1.089992540745676,
  'time': 150.49,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553730,
   'result': 'BODYMASS_RELATIVE_ECC_DECEL_IMPULSE',
   'description': 'Net impulse from the start of eccentric deceleration to the end of the eccentric phase relative to body mass',
   'name': 'Eccentric Deceleration Impulse / BM',
   'unit': 'Newton Second Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553731,
  'value': 10.74348117515394,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553731,
   'result': 'DISPLACEMENT_AT_TAKEOFF',
   'description': 'Displacement of the centre of mass when takeoff occurs',
   'name': 'Displacement at Takeoff',
   'unit': 'Centimeter',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553732,
  'value': 25.54645447118883,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553732,
   'result': 'BM_REL_FORCE_AT_ZERO_VELOCITY',
   'description': 'The combined force at the instant velocity is zero divided by body mass',
   'name': 'Force at Zero Velocity / BM',
   'unit': 'Newton Per Kilo',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553733,
  'value': 44.18425092575009,
  'time': 151.472,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553733,
   'result': 'RSI_MODIFIED_IMP_MOM',
   'description': 'Jump height (Imp-Mom) / Contraction time',
   'name': 'RSI-modified (Imp-Mom)',
   'unit': 'RSIModified',
   'repeatable': False,
   'asymmetry': False}},
 {'resultId': 6553734,
  'value': 5.416701338050699,
  'time': 150.642,
  'limb': 'Trial',
  'repeat': 0,
  'definition': {'id': 6553734,
   'result': 'BM_REL_ABS_CON_IMPULSE',
   'description': 'Absolute concentric impulse (area under the Fz curve from the transition point at zero velocity) divided by body mass',
   'name': 'Concentric Impulse (Abs) / BM',
   'unit': 'Newton Second',
   'repeatable': False,
   'asymmetry': False}}]